QTP_BIND_ADDRESS = "0.0.0.0"
QTP_TCP_PORT = 5000
SOCKET_TIMEOUT = 60
# Board-specific mappings must be supplied before hardware tests are added.
GPIO_MAPPING = {}

SELEC_EM4M_PORT = "/dev/ttyCH9344USB4"
SELEC_EM4M_BAUDRATE = 9600
SELEC_EM4M_SLAVE_ID = 1
SELEC_EM4M_TIMEOUT = 0.3
SELEC_EM4M_VOLTAGE_TOLERANCE = 1.0

EDC2150_PORT = "/dev/ttyCH9344USB1"
EDC2150_BAUDRATE = 9600
EDC2150_SLAVE_ID = 2
EDC2150_TIMEOUT = 0.5

IMD1_PORT = "/dev/ttyCH9344USB0"
IMD1_BAUDRATE = 9600
IMD1_PARITY = "N"
IMD1_SLAVE_ID = 5
IMD1_TIMEOUT = 1.0
IMD1_UNDERVOLTAGE_ALARM_THRESHOLD_V = 10
IMD1_OVERVOLTAGE_ALARM_THRESHOLD_V = 1100

IMD2_PORT = "/dev/ttyCH9344USB2"
IMD2_BAUDRATE = 9600
IMD2_PARITY = "N"
IMD2_SLAVE_ID = 4
IMD2_TIMEOUT = 1.0
IMD2_UNDERVOLTAGE_ALARM_THRESHOLD_V = 30
IMD2_OVERVOLTAGE_ALARM_THRESHOLD_V = 500

CAN_CHANNEL = "mcu_mcan0"
CAN_BUSTYPE = "socketcan"
CAN_BITRATE = 125000
CAN_DBC_PATH = "tonhe_can_messages_6modules.csv"
CAN_AUTO_CONFIGURE = True
CAN_RESTART_MS = 100
CAN_DEFAULT_GROUP = 1
CAN_DEFAULT_VOLTAGE = 500.0
CAN_DEFAULT_CURRENT = 41.0
CAN_DEFAULT_MODULE_ADDRESS = 1
CAN_KEEP_ALIVE_INTERVAL = 5.0

RFID_PORT = "/dev/ttyUSB0"
RFID_BAUDRATE = 115200
RFID_TIMEOUT = 1.0
RFID_COMMAND_HEX = "02 00 02 34 31 03 06" #Get Mefare1 card serial number
RFID_ATTEMPTS = 20
RFID_INTERVAL = 0.1
RFID_READ_SIZE = 100

PHYVERSO_CLI = "phyverso_cli"
PHYVERSO_CONFIG_PATH = "/root/config.json"
TEMP_SENSOR_SERIAL_PORT = "/dev/ttyS6"
TEMP_SENSOR_COMMAND = "T"
TEMP_SENSOR_STARTUP_WAIT = 2.0
TEMP_SENSOR_READ_TIMEOUT = 12.0

FOURG_INTERFACE = "wwu1u1i4"
FOURG_QMI_DEVICE = "/dev/cdc-wdm0"
FOURG_APN = "airtelgprs.com"
FOURG_QMI_CONFIG = "/etc/qmi-network.conf"
FOURG_PING_HOST = "google.com"
FOURG_PING_COUNT = 4

RELAY_MCU_SERIAL_PORT = "/dev/ttyS6"
RELAY_MCU_BAUDRATE = 115200
RELAY_FLASHER = "MSPM0_bsl_flasher"
RELAY_COIL_CONTROL_BIN = str(__import__("pathlib").Path(__file__).resolve().parent / "MCU_binary" / "Coil_Control.bin")
RELAY_DEFAULT_BIN = "/usr/lib/firmware/Phytec_MSP_DC.bin"
RELAY_FLASH_TIMEOUT = 90
RELAY_UART_TIMEOUT = 5
